repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [ --fix ]
        exclude: ^(README\.md|ARCHITECTURE\.md|\.github/.*)$
      - id: ruff-format
        exclude: ^(README\.md|ARCHITECTURE\.md|\.github/.*)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        # Mypy будет автоматически читать настройки из твоего pyproject.toml
        args: [ --config-file, pyproject.toml ]
        # Важно: Mypy должен видеть твои зависимости,
        # поэтому указываем, что он должен запускаться в том же окружении
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - sqlalchemy
          - fastapi

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
        exclude: ^(README\.md|ARCHITECTURE\.md)$
      - id: trailing-whitespace
        exclude: ^(README\.md|ARCHITECTURE\.md)$
