"""Initial setup

Revision ID: 8fb7678d5843
Revises:
Create Date: 2026-03-05 17:39:32.149632

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8fb7678d5843"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
