"""Add products table

Revision ID: b04c0f657c88
Revises: c05050d5d6ba
Create Date: 2026-03-06 16:51:52.333229

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b04c0f657c88"
down_revision: Union[str, Sequence[str], None] = "b482551fe84c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
