name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pyflow_oms
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # --- ДЛЯ ТЕСТОВ CELERY ---
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pyflow_oms
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      ALGORITHM: "HS256"
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: poetry install --no-root

    # --- Динамическая генерация SECRET_KEY ---
    - name: Generate dynamic SECRET_KEY for tests
      run: |
        echo "SECRET_KEY=$(python -c 'import secrets; print(secrets.token_hex(32))')" >> $GITHUB_ENV

    - name: Run Ruff Linter
      run: poetry run ruff check src tests

    - name: Run Mypy (Type Check)
      run: poetry run mypy src

    - name: Run Pytest
      run: poetry run pytest -v

  deploy_docs:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Нужно для mkdocs, чтобы видеть историю

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Project Dependencies
        # Нам нужны все зависимости, чтобы mkdocstrings мог импортировать код
        run: poetry install

      - name: Deploy Docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          export PYTHONPATH=$PYTHONPATH:$(pwd)

          poetry run mkdocs gh-deploy --force
